name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m textblob.download_corpora

    - name: Run Flake8 Linter
      run: |
        # Stop build if there are syntax errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat other errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Pytest
      run: |
        pytest

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag sentiment-app:latest
